
-- Q1. What is the total revenue generated by male vs. female customers?

SELECT * FROM customer_behavior.customer;
 select gender,sum(purchase_amount) as revenue 
 from customer_behavior.customer 
 group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select avg(purchase_amount) from customer_behavior.customer;
 select avg(purchase_amount) from customer_behavior.customer;
select customer_id , purchase_amount from customer_behavior.customer
where discount_applied = 'Yes'  and purchase_amount >= (select avg(purchase_amount)
 from customer_behavior.customer);


--  Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as avg_review_rating from customer_behavior.customer 
 group by item_purchased 
 order by avg(review_rating) desc 
 limit 5;
 
 -- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
 
 select shipping_type ,round(avg(purchase_amount),2) 
 from customer_behavior.customer 
 where shipping_type in( 'standard', 'express')
 group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as AVG_SPEND ,
round(sum(purchase_amount),2) as TOTAL_REVENUE 
from customer_behavior.customer group by subscription_status
 order by round(avg(purchase_amount),2),round(sum(purchase_amount),2) desc ;
 
 -- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT * FROM customer_behavior.customer;
select item_purchased,
round(100* sum(case when discount_applied = 'Yes' 
then 1 else 0 end )/count(*),2) as discount_rate 
 from customer_behavior.customer
 group by item_purchased 
 order by discount_rate desc 
 limit 5;
SELECT * FROM customer_behavior.customer;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id , previous_purchases,
case 
	when previous_purchases  = 1 then 'new' 
	when previous_purchases  between 2 and 10 then 'returner '
	else ' loyal'
	end  as  segement_customers from customer_behavior.customer)
    
select segement_customers ,count(*) as 'Number of Customers' 
from customer_type 
group by segement_customers;
 
-- Q8. What are the top 3 most purchased products within each category?
SELECT * FROM customer_behavior.customer;


with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders, 
row_number() over(partition by category 
order by count(customer_id) desc) as item_rank
from customer_behavior.customer
group by category, item_purchased
)

select  item_rank,category, item_purchased,total_orders 
from item_counts 
where item_rank <= 3;
-- -- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select  subscription_status,count(customer_id) as repeat_buyers
from customer_behavior.customer
 where previous_purchases > 5 group by subscription_status;


-- Q10. What is the revenue contribution of each age group?
select sum(purchase_amount) as total_revenue , age_group from customer_behavior.customer 
 group by age_group order by total_revenue desc